apiVersion: v1
kind: Service
metadata:
  name: todos-grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  ports:
  - name: grafana
    targetPort: grafana
    port: 3000
  selector:
    app: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-grafana
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        name: grafana
    spec:
      restartPolicy: Always
      containers:
        - name: todos-grafana
          image: grafana/grafana:8.3.3
          ports:
            - name: grafana
              containerPort: 3000
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
