apiVersion: v1
kind: Service
metadata:
  name: todos-prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  ports:
  - name: prometheus
    targetPort: prometheus
    port: 9090
  selector:
    app: prometheus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todos-prometheus-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: todos-prometheus
          image: prom/prometheus
          args:
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - name: prometheus
              containerPort: 9090
          volumeMounts:
            - name: prometheus-storage
              mountPath: /prometheus/
      volumes:
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: todos-prometheus-claim
