version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web/"
    schedule:
      interval: "weekly"
      time: "08:00"
    open-pull-requests-limit: 50
    labels:
      - npm
      - dependabot

  - package-ecosystem: "pip"
    directory: "/server/"
    schedule:
      interval: "weekly"
      time: "08:00"
    open-pull-requests-limit: 50
    labels:
      - pip
      - dependabot
