version: "3.9"

services:
  web:
    build:
      context: "./web"
      target: "development"
    container_name: todos-web
    restart: on-failure
    working_dir: "/web/"
    command: "scripts/start-dev.sh"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "development"
    networks:
      - todos-web
      - todos-proxy
    volumes:
      - ./web:/web
      - /web/node_modules
    depends_on:
      - server

  server:
    build:
      context: "./server"
      target: "development"
    container_name: todos-server
    restart: on-failure
    command: "scripts/start-dev.sh"
    working_dir: "/server/"
    environment:
      DEBUG: true
      DATABASE_URL: "mysql+mysqldb://todos:todos@mysql:3306/todos"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      SECRET_KEY: "secret"
    volumes:
      - ./server:/server
    ports:
      - "5000:5000"
      - "8181:8181"
    networks:
      - todos-server
      - todos-proxy
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: todos-mysql
    restart: on-failure
    environment:
      MYSQL_USER: "todos"
      MYSQL_ROOT_PASSWORD: "todos"
      MYSQL_PASSWORD: "todos"
      MYSQL_DATABASE: "todos"
    networks:
      - todos-server
    volumes:
      - ./data/mysql:/var/lib/mysql

networks:
  todos-server:
    driver: bridge
  todos-web:
    driver: bridge
  todos-proxy:
    driver: bridge
