version: "3.9"

services:
  frontend:
    build:
      target: "development"
    command: "scripts/start-local.sh"
    environment:
      NODE_ENV: "development"
    ports:
      - "3000:3000"

  base-app:
    build:
      context: "./backend"
      target: "development"
    environment:
      DEBUG: "true"
      DATABASE_URL: "mysql+mysqldb://todos:todos@mysql:3306/todos"
      METRICS_PORT: 8181
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_EXPIRES: 60
      CELERY_RESULT_BACKEND: "redis://redis:6379/1"

  backend:
    command: "scripts/start-local.sh"
    ports:
      - "8000:8000"

  worker:
    ports:
      - "8080:8080"

  mysql:
    environment:
      MYSQL_USER: "todos"
      MYSQL_ROOT_PASSWORD: "todos"
      MYSQL_PASSWORD: "todos"
      MYSQL_DATABASE: "todos"
    ports:
      - "3306:3306"

  redis:
    environment:
      REDIS_PASSWORD: "todos"
    ports:
      - "6379:6379"
