version: "3.9"

services:
  nginx:
    image: nginx:1.21-alpine
    container_name: todos-nginx
    restart: always
    networks:
      - todos-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    command: pipenv run gunicorn todos --bind=0.0.0.0:8080
    environment:
      FLASK_DEBUG: "false"
      FLASK_ENV: production
    networks:
      - todos-main
      - todos-proxy

networks:
  todos-proxy:
    driver: bridge