version: "3.9"

services:
  web:
    build:
      context: "./web"
      target: "development"
    container_name: todos-web
    restart: on-failure
    working_dir: "/web/"
    command: "scripts/start-dev.sh"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "development"
    networks:
      - todos-web
    volumes:
      - ./web:/web
      - /web/node_modules
    depends_on:
      - server

  server:
    build:
      context: "./server"
      target: "development"
    container_name: todos-server
    restart: on-failure
    command: "scripts/start-dev.sh"
    working_dir: "/server/"
    environment:
      DEBUG: true
      DATABASE_URL: "postgresql+psycopg2://todos:todos@postgres:5432/todos"
      SECRET_KEY: "secret"
    volumes:
      - ./server:/server
    ports:
      - "5000:5000"
      - "8181:8181"
    networks:
      - todos-server
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    container_name: todos-postgres
    restart: on-failure
    environment:
      POSTGRES_USER: "todos"
      POSTGRES_PASSWORD: "todos"
      POSTGRES_DB: "todos"
    networks:
      - todos-server
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

networks:
  todos-server:
    driver: bridge
  todos-web:
    driver: bridge
