version: "3.9"

services:
  nginx:
    image: nginx:1.21-alpine
    container_name: todos-nginx
    restart: always
    networks:
      - todos-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build: "."
    container_name: todos-app
    restart: always
    command: "./scripts/start-app.sh"
    networks:
      - todos-main
      - todos-proxy
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14-alpine
    container_name: todos-postgres
    restart: always
    networks:
      - todos-main
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    container_name: todos-redis
    restart: always
    networks:
      - todos-main
    volumes:
      - ./data/redis:/data

networks:
  todos-main:
    driver: bridge
