version: "3.9"

services:
  app:
    build: "."
    container_name: todos-app
    restart: always
    networks:
      - todos-main
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14-alpine
    container_name: todos-postgres
    restart: always
    networks:
      - todos-main
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    container_name: todos-redis
    restart: always
    networks:
      - todos-main
    volumes:
      - ./data/redis:/data

networks:
  todos-main:
    driver: bridge