version: "3.9"

services:
  frontend:
    build:
      target: "development"
    command: "scripts/start-local.sh"
    environment:
      NODE_ENV: "development"
    ports:
      - "3000:3000"

  backend:
    build:
      target: "development"
    command: "scripts/start-local.sh"
    environment:
      FASTAPI_DEBUG: "true"
      ELASTICSEARCH_URL: "http://elastic:todos@elastic:9200"
      DATABASE_URL: "postgresql+asyncpg://todos:todos@postgres:5432/todos"
    ports:
      - "8000:8000"

  postgres:
    environment:
      POSTGRES_USER: "todos"
      POSTGRES_PASSWORD: "todos"
      POSTGRES_DB: "todos"
    ports:
      - "5432:5432"

  redis:
    environment:
      REDIS_PASSWORD: "todos"
    ports:
      - "6379:6379"

  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_USER: "todos"
      RABBITMQ_DEFAULT_PASS: "todos"
    ports:
      - "5672:5672"

  elasticsearch:
    environment:
      ELASTIC_PASSWORD: "todos"
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      xpack.security.enabled: "true"
    ports:
      - "9200:9200"
