version: "3.9"

services:
  nginx:
    image: nginx:1.21-alpine
    container_name: todos-nginx
    restart: always
    networks:
      - todos-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build: "."
    container_name: todos-app
    restart: always
    command: "./scripts/start-app.sh"
    environment:
      FLASK_DEBUG: "false"
      FLASK_ENV: production
      FLASK_APP: "todos:application"
      SESSION_COOKIE_SECURE: "${SESSION_COOKIE_SECURE:-false}"
      DATABASE_URL: "${DATABASE_URL}"
      CACHE_TYPE: "${CACHE_TYPE:-RedisCache}"
      CACHE_DEFAULT_TIMEOUT: "${CACHE_DEFAULT_TIMEOUT:-300}"
      CACHE_REDIS_URL: "${CACHE_REDIS_URL}"
      SECRET_KEY: "${SECRET_KEY}"
    networks:
      - todos-main
      - todos-proxy
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14-alpine
    container_name: todos-postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    networks:
      - todos-main
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    container_name: todos-redis
    restart: always
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    networks:
      - todos-main
    volumes:
      - ./data/redis:/data

networks:
  todos-main:
    driver: bridge
  todos-proxy:
    driver: bridge
