version: "3.9"

services:
  web:
    build:
      context: "./web"
      target: "development"
    container_name: todos-web
    restart: on-failure
    working_dir: "/web/"
    command: "scripts/start-dev.sh"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "development"
    networks:
      - todos-web
      - todos-proxy
    volumes:
      - ./web:/web
      - /web/node_modules
    depends_on:
      - server

  base-app:
    build:
      context: "./server"
      target: "development"
    working_dir: "/server/"
    environment:
      DEBUG: true
      DATABASE_URL: "mysql+mysqldb://todos:todos@mysql:3306/todos"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      SECRET_KEY: "secret"
    volumes:
      - ./server:/server

  server:
    extends:
      service: base-app
    container_name: todos-server
    restart: on-failure
    command: "scripts/start-dev.sh"
    ports:
      - "5000:5000"
      - "8181:8181"
    networks:
      - todos-server
      - todos-proxy
    depends_on:
      - mysql

  worker:
    extends:
      service: base-app
    container_name: todos-worker
    restart: always
    command: "scripts/run-worker.sh"
    ports:
      - "8080:8080"
    networks:
      - todos-server
    depends_on:
      - redis
      - server

  mysql:
    image: mysql:8
    container_name: todos-mysql
    restart: on-failure
    environment:
      MYSQL_USER: "todos"
      MYSQL_ROOT_PASSWORD: "todos"
      MYSQL_PASSWORD: "todos"
      MYSQL_DATABASE: "todos"
    networks:
      - todos-server
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    image: redis:6.2-alpine
    container_name: todos-redis
    restart: on-failure
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "todos"
    networks:
      - todos-server
    volumes:
      - ./data/redis:/data

networks:
  todos-server:
    driver: bridge
  todos-web:
    driver: bridge
  todos-proxy:
    driver: bridge
