version: "3.9"

services:
  nginx:
    image: nginx:1.21-alpine
    container_name: todos-nginx
    restart: always
    networks:
      - todos-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build: "."
    container_name: todos-app
    restart: always
    command: pipenv run gunicorn todos --bind=0.0.0.0:8080
    environment:
      FLASK_DEBUG: "true"
      FLASK_ENV: development
      SESSION_COOKIE_SECURE: "false"
      DATABASE_URL: postgresql://todos:todos@postgres:5432/todos/
      CACHE_TYPE: RedisCache
      CACHE_DEFAULT_TIMEOUT: 300
      CACHE_REDIS_URL: redis://:todos@localhost:6379/
      SECRET_KEY: secretkey
    networks:
      - todos-main
      - todos-proxy
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14-alpine
    container_name: todos-postgres
    restart: always
    environment:
      POSTGRES_USER: todos
      POSTGRES_PASSWORD: todos
      POSTGRES_DB: todos
    networks:
      - todos-main
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    container_name: todos-redis
    restart: always
    environment:
      REDIS_PASSWORD: todos
    networks:
      - todos-main
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

networks:
  todos-main:
    driver: bridge
  todos-proxy:
    driver: bridge