version: "3.9"

services:
  nginx:
    ports:
      - "80:80"

  app:
    environment:
      FLASK_DEBUG: "false"
      FLASK_ENV: production
      FLASK_APP: "todos:application"
      SESSION_COOKIE_SECURE: "${SESSION_COOKIE_SECURE:-false}"
      DATABASE_URL: "${DATABASE_URL}"
      CACHE_TYPE: "${CACHE_TYPE:-RedisCache}"
      CACHE_DEFAULT_TIMEOUT: "${CACHE_DEFAULT_TIMEOUT:-300}"
      CACHE_REDIS_URL: "${CACHE_REDIS_URL}"
      SECRET_KEY: "${SECRET_KEY}"
    expose:
      - "8000"
    networks:
      - todos-main
      - todos-proxy

  postgres:
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

  redis:
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
