version: "3.9"

services:
  frontend:
    build:
      context: "./frontend"
      target: "production"
    container_name: todos-frontend
    restart: on-failure
    working_dir: "/frontend/"
    command: "scripts/start-prod.sh"
    environment:
      NODE_ENV: "production"
    networks:
      - todos-frontend
      - todos-proxy
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend

  base-app:
    build:
      context: "./backend"
      target: "production"
    working_dir: "/backend/"
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      DATABASE_URL: "${DATABASE_URL}"
      MAIL_SERVER: "${MAIL_SERVER}"
      MAIL_PORT: "${MAIL_PORT}"
      MAIL_DEFAULT_SENDER: "${MAIL_DEFAULT_SENDER}"
      MAIL_USE_TLS: "${MAIL_USE_TLS}"
      MAIL_USERNAME: "${MAIL_USERNAME}"
      MAIL_PASSWORD: "${MAIL_PASSWORD}"
    volumes:
      - ./backend:/backend

  backend:
    extends:
      service: base-app
    container_name: todos-backend
    restart: on-failure
    command: "scripts/start-prod.sh"
    networks:
      - todos-backend
      - todos-proxy
    depends_on:
      - mysql

  worker:
    extends:
      service: base-app
    container_name: todos-worker
    restart: always
    command: "scripts/run-worker.sh"
    networks:
      - todos-backend
    depends_on:
      - redis
      - backend

  mysql:
    image: mysql:8
    container_name: todos-mysql
    restart: on-failure
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    networks:
      - todos-backend
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    image: redis:6.2-alpine
    container_name: todos-redis
    restart: on-failure
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    networks:
      - todos-backend
    volumes:
      - ./data/redis:/data

networks:
  todos-backend:
    driver: bridge
  todos-frontend:
    driver: bridge
  todos-proxy:
    driver: bridge
