version: "3.9"

services:
  frontend:
    build:
      context: "./frontend"
      target: "development"
    container_name: todos-frontend
    restart: on-failure
    working_dir: "/frontend/"
    command: "scripts/start-dev.sh"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "development"
    networks:
      - todos-frontend
      - todos-proxy
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend

  base-app:
    build:
      context: "./backend"
      target: "development"
    working_dir: "/backend/"
    environment:
      DEBUG: true
      DATABASE_URL: "mysql+mysqldb://todos:todos@mysql:3306/todos"
      METRICS_PORT: 8181
      CELERY_BROKER_URL: "redis://redis:6379/0"
    volumes:
      - ./backend:/backend

  backend:
    extends:
      service: base-app
    container_name: todos-backend
    restart: on-failure
    command: "scripts/start-dev.sh"
    ports:
      - "8000:8000"
      - "8181:8181"
    networks:
      - todos-backend
      - todos-proxy
    depends_on:
      - mysql

  worker:
    extends:
      service: base-app
    container_name: todos-worker
    restart: always
    command: "scripts/run-worker.sh"
    ports:
      - "8080:8080"
    networks:
      - todos-backend
    depends_on:
      - redis
      - backend

  mysql:
    image: mysql:8
    container_name: todos-mysql
    restart: on-failure
    environment:
      MYSQL_USER: "todos"
      MYSQL_ROOT_PASSWORD: "todos"
      MYSQL_PASSWORD: "todos"
      MYSQL_DATABASE: "todos"
    networks:
      - todos-backend
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    image: redis:6.2-alpine
    container_name: todos-redis
    restart: on-failure
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "todos"
    networks:
      - todos-backend
    volumes:
      - ./data/redis:/data

networks:
  todos-backend:
    driver: bridge
  todos-frontend:
    driver: bridge
  todos-proxy:
    driver: bridge
