apiVersion: v1
kind: ConfigMap
metadata:
  name: todos-config-map
data:
  db_port: "3306"
  database: todos
  db_user: todos
  db_password: todos
  db_url: mysql+mysqldb://todos:todos@todos-mysql:3306/todos