apiVersion: v1
kind: Service
metadata:
  name: todos-mysql
spec:
  clusterIP: None
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector:
    app: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todos-mysql-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      restartPolicy: Always
      containers:
        - name: todos-mysql
          image: mysql:8
          ports:
            - name: mysql
              containerPort: 3306              
          env:
            - name: MYSQL_DATABASE
              valueFrom:
              configMapKeyRef:
                name: todos-config
                key: db_name
            - name: MYSQL_PASSWORD
              configMapKeyRef:
                name: todos-config
                key: db_password
            - name: MYSQL_ROOT_PASSWORD
              configMapKeyRef:
                name: todos-config
                key: db_root_password
            - name: MYSQL_USER
              configMapKeyRef:
                name: todos-config
                key: db_username
          resources:
            requests:
              memory: "500Mi"
              cpu: "300m"
            limits:
              memory: "500Mi"
              cpu: "300m"
          livenessProbe:
            tcpSocket:
              port: mysql
            initialDelaySeconds: 5
            periodSeconds: 15
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: todos-mysql-claim
