apiVersion: v1
kind: Service
metadata:
  name: todos-mysql
spec:
  clusterIP: None
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todos-mysql-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: todos-mysql-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-volume-claim
      containers:
        - name: todos-mysql
          image: mysql:8
          ports:
            - name: mysql
              containerPort: 3306              
          env:
            - name: MYSQL_DATABASE
              valueFrom:
              configMapKeyRef:
                name: todos-config
                key: db_name
            - name: MYSQL_PASSWORD
              configMapKeyRef:
                name: todos-config
                key: db_password
            - name: MYSQL_ROOT_PASSWORD
              configMapKeyRef:
                name: todos-config
                key: db_root_password
            - name: MYSQL_USER
              configMapKeyRef:
                name: todos-config
                key: db_username
          resources:
            requests:
              memory: "500Mi"
              cpu: "300m"
            limits:
              memory: "500Mi"
              cpu: "300m"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      restartPolicy: Always
