apiVersion: v1
kind: Service
metadata:
  name: todos-redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      targetPort: redis
      port: 6397
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      restartPolicy: Always
      containers:
        - name: todos-redis
          image: redis:6.2-alpine
          ports:
            - name: redis
              containerPort: 6379
          resources:
            requests:
              memory: 256Mi
              cpu: 125m
            limits:
              memory: 200Mi
              cpu: 70m
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            periodSeconds: 15
