name: backend tests

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  tests:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./backend
    env:
      DEBUG: true
      DATABASE_URL: "sqlite://"
      MAIL_SUPPRESS_SEND: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Pipenv
        run: pip install --no-cache pipenv

      - name: Install Dependencies
        run: pipenv install --dev

      - name: Run Tests
        run: sh ./scripts/run-tests.sh
