name: backend tests

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  tests:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./backend
    env:
      FLASK_TESTING: true
      MAIL_SUPPRESS_SEND: true
      SECRET_KEY: "secret"
      DATABASE_URL: "mysql+mysqldb://todos:todos@127.0.0.1:3306/todos"

    services:
      mysql:
        image: mysql:8
        ports:
          - "3306:3306"
        env:
          MYSQL_USER: "todos"
          MYSQL_ROOT_PASSWORD: "todos"
          MYSQL_PASSWORD: "todos"
          MYSQL_DATABASE: "todos"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Pipenv
        run: pip install --no-cache pipenv

      - name: Install Dependencies
        run: pipenv install --dev

      - name: Run Tests
        run: sh ./scripts/run-tests.sh
