name: backend:tests

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  tests:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./backend

    services:
      mysql:
        image: mysql:8
        ports:
          - "3306:3306"
        env:
          MYSQL_USER: "todos"
          MYSQL_PASSWORD: "todos"
          MYSQL_DATABASE: "todos"

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install pipenv
        run: pip install --no-cache pipenv

      - name: install dependencies
        run: pipenv install --dev

      - name: run tests
        run: ./scripts/run-tests.sh

      - name: upload coverage
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          verbose: true
