name: server tests

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
  pull_request:
    branches:
      - main
    paths:
      - "server/**"

jobs:
  tests:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./server
    env:
      DEBUG: true
      DATABASE_URL: "postgresql+psycopg2://todos:todos@127.0.0.1:5432/todos"
      SECRET_KEY: "secret"

    services:
      mysql:
        image: postgres:14-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: "todos"
          POSTGRES_PASSWORD: "todos"
          POSTGRES_DB: "todos"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Pipenv
        run: pip install --no-cache pipenv

      - name: Install Dependencies
        run: pipenv install --dev

      - name: Run Tests
        run: sh ./scripts/run-tests.sh
