name: web tests

on:
  push:
    branches:
      - main
    paths:
      - "web/**"
  pull_request:
    branches:
      - main
    paths:
      - "web/**"

jobs:
  tests:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Tests
        run: sh ./scripts/run-tests.sh
